// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdztxlpttisybquygfep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkenR4bHB0dGlzeWJxdXlnZmVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMTg3MDEsImV4cCI6MjA2MDg5NDcwMX0._Wkv2yXdKJB6_ZZKe4FqNEFr9gn0ndtptLdXNQLfU-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);